# Exceções
São criadas quando uma situação inválida é detectada. Uma vez criada, é lançada na pilha de execução (`stack`).
As funções que estão na pilha recebem a exceção e podem capturá-la ou não. Caso não capturem a função é abortada e a exceção passa para a próxima função. Esse processo
<!--stackedit_data:
eyJoaXN0b3J5IjpbLTg2ODQzMDExNF19
-->