# Exceções
São criadas quando uma situação inválida é detectada. Uma vez criada, é lançada na pilha de execução (`stack`).
As funções que estão na pilha recebem a exceção e podem capturá-la ou não. Caso não capturem a função é abortada e a exceção passa para a próxima função. Esse processo continua até que a exceção seja capturada ou até chegar à função `main`. Se não for capturada na função `main`, ela também é abortada e o programa encerrado.

## Pilha de execução (`stack`)
É uma área de memória reservada para uso das funções que estão em execução.

> Heap (alocação dinâmica)

| Heap  |
|--|
|  |
| Stack |

> Stack - Área de memória reservada para as funções em execução (hierarquia)

## Estrutura Try-Catch-Finally

Usada para capturar exceções.
No bloco `try` é colocado o código que será protegido. Este código é executado até o ponto onde a exceção ocorreu
<!--stackedit_data:
eyJoaXN0b3J5IjpbMTUxNjIxMTAwNF19
-->